### ISSUE TITLE
No metadata informations can be retrieved

### ISSUE THREAD

**Issue by adrienyhuel** [ServerCentral/praeco#100]
I can't see any query, alert or error history in Praeco.

It seems that elastalert-server try to make a query only in writeback index.
But for ES6, elastalert create multiple indexes (_status, _error, ...), so elastalert-server should look into those specific indexes.

See https://github.com/ServerCentral/elastalert-server/blob/folders/src/handlers/metadata/get.js

**Comment by johnsusek** [comment]
ElastAlert only creates one index. elastalert_status, elastalert_error, are _types_. 

As far as troubleshooting why you're not getting any logs - 

Is your writeback_index the same in api.config.json and elastalert.yaml?

**Comment by youlJunior** [comment]
@johnsusek 
For ES > 5, elastalert creates multiple indexes, as types is deprecated.
See : https://github.com/Yelp/elastalert/blob/master/elastalert/create_index.py

I created an issue in bitsensor/elastalert, as your code is pulled from his code.

**Comment by youlJunior** [comment]
Do you want to let bitsensor to modify his code, or maybe want help to modify it yourself ?

**Comment by johnsusek** [comment]
Fixed in pr, thanks @adrienyhuel
