### ISSUE TITLE
Praeco GUI getting 'Internal error TypeError: n is null'

### ISSUE THREAD

**Issue by sir-wally** [ServerCentral/praeco#104]
Hi I installed praeco following these instructions [https://medium.com/@john_8166/praeco-walkthrough-5aada7e078a9](url) on ubuntu-server 18.04 and I'm seeing the error in the web gui. Thanks 

![internal_error](https://user-images.githubusercontent.com/37912176/53525998-f405bc00-3a97-11e9-94ef-015a91a7d5aa.PNG)

only error I see in the container's logs is below: 

#docker logs -f praeco_webapp_1
nginx: [emerg] host not found in upstream "elastalert" in /etc/nginx/conf.d/default.conf:10

the issue persists after a reboot, however it doesn't appear to have any impact on rule functionality as all my alerts are working

**Comment by johnsusek** [comment]
It looks like the instructions in that article are a little out of date. I edited it to instruct the user to checkout the repo and run from there, instead of downloading a release zip. You are likely running an older version of praeco. 

Can you try to install again using the new instructions (only the download instructions at the top of the article have changed). If you have a lot of rules you can copy them over from the `rules` folder instead of recreating them.

**Comment by adrienyhuel** [comment]
I have a similar problem here : 
![snip_20190312222013](https://user-images.githubusercontent.com/14916484/54236932-1cb89780-4515-11e9-82b6-76a816480a46.png)

**Comment by sir-wally** [comment]
> 
> 
> It looks like the instructions in that article are a little out of date. I edited it to instruct the user to checkout the repo and run from there, instead of downloading a release zip. You are likely running an older version of praeco.
> 
> Can you try to install again using the new instructions (only the download instructions at the top of the article have changed). If you have a lot of rules you can copy them over from the `rules` folder instead of recreating them.

Thanks for taking a look at the issue, unfortunately I'm still getting the same error after reinstalling. @adrienyhuel nailed it, it's only for rules of types "count" and "average" where we used GROUPED OVER

**Comment by johnsusek** [comment]
Okay thanks, I will take a look!

**Comment by adrienyhuel** [comment]
I think the issue #79 is linked to this one too.

**Comment by johnsusek** [comment]
Been working on this issue. Determined the root cause is related to grouping on analyzed vs. non-analyzed fields. The fix is to add e.g. .raw or .keyword to the field name when constructing the ES query for the chart. There is a way to determine this from the mapping, just requires some work.

**Comment by johnsusek** [comment]
@adrienyhuel @sir-wally Just pushed a new release that fixes an issue building the chart for GROUPED OVER conditions. Can you try again and see if it fixes this error for you? Note when selecting a field to group over, you'll want to choose the one suffixed with e.g. `.keyword` or `.raw`.

**Comment by adrienyhuel** [comment]
@johnsusek I just updated praeco, no errors anymore.
Great work !

**Comment by johnsusek** [comment]
Great, glad to hear!
