### ISSUE TITLE
Alerts are only sent to first email recipient

### ISSUE THREAD

**Issue by adrienyhuel** [ServerCentral/praeco#106]
Only first recipient receive emails.

It is because Praeco doesn't format yml correctly for email.

what Praeco write : 
`email: 'recipient1@email.com,recipient2@email.com'`

what Elastalert require : 
```
email:
  - "recipient1@email.com"
  - "recipient2@email.com"
```

**Comment by johnsusek** [comment]
Good catch! Fixed in master

**Comment by adrienyhuel** [comment]
@johnsusek 
I tested, this is OK.
But there is the same problem with CC and BCC emails, can you resolve it too ?

**Comment by adrienyhuel** [comment]
@johnsusek do you want me to open a new issue for CC and BCC emails ?

**Comment by johnsusek** [comment]
nah, I will re-open this one

**Comment by johnsusek** [comment]
fixed
