### ISSUE TITLE
Elastalert Host Unreachable [113]

### ISSUE THREAD

**Issue by DanielLeeJM** [ServerCentral/praeco#115]
Hi, I am experimenting with Elastalert on a school project but im encountering some issues.
I have a CENTOS7 Virtual Machine running on Oracle VM Virtualbox Manager with Elasticsearch and Kibana running and working fine. Similarly, I have praeco and all its dependencies installed.
My Elasticsearch server is exposed at 192.168.122.1:9200 and I can curl and connect to it. 
No issues viewing it from kibana either, but praeco fails when running docker-compose up.

The relevant failure is:
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='192.168.122.1', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5463d6dd0>: Failed to establish a new connection: [Errno 113] Host is unreachable',))) caused by: ConnectionError(HTTPConnectionPool(host='192.168.122.1', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe5463d6dd0>: Failed to establish a new connection: [Errno 113] Host is unreachable',)))

I've tried to open firewalls and the like, but as far as I am aware once I perform:

export $PRAECO_ELASTICSEARCH=192.168.122.1
docker-compose up

It should work, but every time it does so, the elastalert server cant seem to connect.
I've tried a number of things, from changing the api.config.json and elastalert.yaml files in the praeco/config, to opening some firewalls and permanently granting http access, to changing the elasticsearch network.host.

I realised whenever starting the compose container a new virtual config is found in ifconfig:

veth734b357: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::1063:89ff:fe92:a26c  prefixlen 64  scopeid 0x20<link>
        ether 12:63:89:92:a2:6c  txqueuelen 0  (Ethernet)
        RX packets 53  bytes 4576 (4.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 81  bytes 11500 (11.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I'm not quite sure how to proceed at this point to fix this issue. Any advice (hopefully simple and clear, I am not very experienced with dockers and virtual machines) would be appreciated. Thank you!

**Comment by johnsusek** [comment]
Just so I understand your environment, do I have this right?
- Your computer (MacOS?) ("the host") is running Virtualbox. 
- Inside Virtualbox you have a CentOS VM running Elasticsearch/Kibana.
- From the host you can curl 192.168.122.1:9200
- The host is also running Docker.

**Comment by johnsusek** [comment]
Are you using bridged networking in virtualbox?

**Comment by DanielLeeJM** [comment]
> Just so I understand your environment, do I have this right?
> 
> * Your computer (MacOS?) ("the host") is running Virtualbox.
> * Inside Virtualbox you have a CentOS VM running Elasticsearch/Kibana.
> * From the host you can curl 192.168.122.1:9200
> * The host is also running Docker.

Windows 10 host is running virtualbox, yes.
That is corect.
From the VM,  I can curl that address.
The docker container for praeco, where i run "docker-compose up" is also running in the VM. Praeco is in the same VM instance as elasticsearch and kibana.  

The networking in virtualbox is NAT network and a Host only Adapter, but I dont think this is relevant to the issue. I am using CURL from the CENTOS Terminal. All work at the moment is done in CENTOS and expected to remain this way.

**Comment by johnsusek** [comment]
So the issue is, you need to be able to curl that address *from the host*. 

Try changing to bridged networking in vbox, which will allow the host to communicate with ES, which means docker running on the host should also be able to communicate with it.

**Comment by johnsusek** [comment]
Okay, I see. If docker is running within the VM you are right the networking probably shouldn't matter, but can you give that a try and see if it changes anything? 

Also, does `curl $PRAECO_ELASTICSEARCH:9200` work?

**Comment by DanielLeeJM** [comment]
Thanks, I changed one of the adapters in the Virtualbox network settings for the VM to bridged networking and now elastalert server did start on localhost:3030. I can now see praeco webapp at 8080 and it says the elastalert is ready. 

Appreciate your assistance.

For future reference, what I did was:
Open Oracle VM VirtualBox Manager
Rightclick on the virtual machine instance that was running.
Click settings.
Click the Network Tab.
Changed the adapter 1 "attached to" Bridged Adapter.
Click Ok.
I can now see both localhost:8080, and localhost:3030 on the Virtual Machine browser.
