### ISSUE TITLE
Filter future dates from activity log

### ISSUE THREAD

**Issue by johnsusek** [ServerCentral/praeco#116]

**Comment by adrienyhuel** [comment]
@johnsusek there is a problem with this enhancement (#665c96c705ab3805eec9ceb60fe5de31450df932).
When the request.params.type is not "elastalert", then the range variable is an empty map.
The, in the "must" list, the first param is the query, and the second one (the range) is empty, and elasticsearch throw an error : "query malformed, empty clause found at [1:129]"

So we can't see the query and silence logs anymore.

**Comment by johnsusek** [comment]
Ok, good catch, I will take a look ASAP

**Comment by johnsusek** [comment]
didn't catch this because we are running ES5 here - will update it to work for ES6 too

**Comment by johnsusek** [comment]
@adrienyhuel Just pushed a fix to elastalert-server, and reorganized the metadata handler: https://github.com/ServerCentral/elastalert-server/commit/63bcc53b1ca1fea3024d6b6fa01943f6a6d3f728#diff-22d73777645d5d82e54cb05703203f24

Can you give it a try and confirm it works on your end too? thx

**Comment by adrienyhuel** [comment]
@johnsusek I just tried it, and it works !
Good job :+1:

**Comment by KhaledFarhat** [comment]
It seems like this change did not make it to the original ElastAlert Repo referenced in the Praeco project, what can i do to get this change in if i am not using the elastalert-server as a standalone and just letting it run the default way from Praeco? 
it seems like the elastalert-server repo is not registered properly and cannot be pulled with docker

**Comment by johnsusek** [comment]
@KhaledFarhat if you follow the upgrade instructions it should pull the latest version of the server-

```
docker pull servercentral/praeco; docker pull servercentral/elastalert
docker-compose up --force-recreate --build; docker image prune -f
```
