### ISSUE TITLE
Missing message body when alert subject is updated

### ISSUE THREAD

**Issue by KevSex** [ServerCentral/praeco#118]
When the alert_subject is updated after creation, the yml format changes within the file causing the message body not to be read correctly.

When I first set up the alert, the config showed:
```
alert_subject: TEST
alert_subject_args: []
alert_text: >
  This is the message body.
alert_text_args: []
```

When I updated the subject, it then updated to:
```
alert_subject: |
  TEST TEST
alert_subject_args: []
alert_text: >
  This is the message body.
alert_text_args: []
```

This causes the alert_text not to be read for some reason.

After a manual change to the config back to the first way, I then attempted to add in a field, which then produced the following config.
```
alert_subject: "TEST -\_ {0}\n"
alert_subject_args:
  - logsource
alert_text: >
  This is the message body.
alert_text_args: []
```

The above appears to work as intended and the alert_text is visible within the email message body.

It looks like there may be an issue when the subject uses the pipe symbol?

**Comment by johnsusek** [comment]
What exactly do you mean by "This causes the alert_text not to be read for some reason." ?

Are you saying in your second example, the email/slack doesn't contain any alert text?

**Comment by KevSex** [comment]
Yes, the email body is empty when this occurs

**Comment by johnsusek** [comment]
In the email with the empty body, what did the subject render as -- "TEST TEST" ?

**Comment by KevSex** [comment]
Yes, the subject was displayed correctly (no additional characters)

**Comment by johnsusek** [comment]
This should be fixed in the latest release - this ended up being part of another bug. Thanks for your report!
