### ISSUE TITLE
Communication error with Elasticsearch

### ISSUE THREAD

**Issue by adrienyhuel** [ServerCentral/praeco#121]
Since last build, there is an error in elastalert-server when communication with elasticsearch.

This is due to an issue in elastalert ( Yelp/elastalert#2203, Yelp/elastalert#2204 )
This will be corrected in when a pull request, but in the meantime can you just apply a patch like https://github.com/HacknowledgeCH/elastalert-docker/commit/58fead0b5be27087a6901a74cc91c09e399995ff ?

BTW, it would be easier if you use versioning, because it's difficult to revert when you only use "latest" tag in your docker images.

**Comment by johnsusek** [comment]
This is already fixed, as of a few minutes ago.

**Comment by adrienyhuel** [comment]
Hehe, good job then !
I test your builds as soon as they are up.
