### ISSUE TITLE
Query Log/Alert Log not being populated

### ISSUE THREAD

**Issue by KhaledFarhat** [ServerCentral/praeco#122]
Hello, 
I have Praeco set up locally, it seems to be connecting to my ElasticSearch instance just fine as i am able to view the data on the graph when trying to create a rule, after the rule is created Praeco still shows the proper data on the graph but it fails to populate any data in the Alert Log, Query Log and Silence Log. As Praeco is running i can see Praeco making calls through the command line that was used to spin it up and it displays the data it should be populating in those different logs but they just don't appear on the UI, please note that I have given Praeco enough time to run and populate the data and created various different rules but none worked.

So all my specific configurations are working as expected but the problem is that the logs are not being populated on the UI so i am not sure which config would be related to this issue. Please let me know which config you would like me to upload and i will do so. 

here is a sample of a rule graph
![image](https://user-images.githubusercontent.com/37488958/56901088-ed2a0400-6a5c-11e9-9aae-b58b4152075e.png)

but it fails to generate any logs
![image](https://user-images.githubusercontent.com/37488958/56901175-2793a100-6a5d-11e9-8d48-34bd4d02b7ff.png)

but its running on the console
![image](https://user-images.githubusercontent.com/37488958/56901791-93c2d480-6a5e-11e9-81ac-ac56046362e1.png)

**Comment by johnsusek** [comment]
Is the rule enabled?

**Comment by johnsusek** [comment]
Can you look in your browser's network inspector and find the elastalert_status call? It should end in rule_name=blah. What are the query string params sent, and what is the response?

**Comment by KhaledFarhat** [comment]
@johnsusek 

1- The rule is Enabled yes
2- The ES instance that i am querying is at "6.2.3", the ES instance i am using for the data write-back is "6.5.4"
3- The Errors tab is blank but the Queries is not, interesting finding i just noticed, the Queries tab was always blank but one of my recent changes triggered a weird behavior. The Queries tab on the left is now displaying data from a separate ElatAlert standalone project that i had set up prior to Praeco to familiarize myself with the project. I am thinking about what could have caused this, i did use the same ElasticSearch server for the data write-back on both, ElastAlert.yaml for Praeco and elastalert-create-index for elastalert
4- the only query string param being sent with the request is the rule name itself, i think this is good but it seems like i am writing the data from a location and trying to retrieve from somewhere else.

so here is the call that is being made for the elastalert_status : http://localhost:8080/api/metadata/elastalert_status?rule_name=test
the data coming back from this only contains data related to the standalone ElastAlert project that i have set up locally and should not be related to Praeco. Are there two different locations where we specify where we want to write the data vs where it should get the history of it from? my understanding that its in the ElastAlert.yaml file only, i will update you if i run into more recent findings.

**Comment by johnsusek** [comment]
are you using the same es_host and writeback_index values in config.json and elastalert.yaml? they should be identical

**Comment by KhaledFarhat** [comment]
Alright that was it, i was using the ES host that i wanted to write data to inside the ElastAlert.yaml, the reason i did that was because there is this text on top of the es_host attribute "# The elasticsearch hostname for metadata writeback", seems like i misunderstood what that line actually meant. 
Thanks for the assistance.
