### ISSUE TITLE
Starting server failed with error

### ISSUE THREAD

**Issue by fvales** [ServerCentral/praeco#139]
When i run docker-compose up, i get the following error:

ERROR elastalert-server:
Server:  Starting server failed with error: TypeError: object must be passed
cdf60ab0f7d4_praeco_elastalert_1 |         at module.exports (/opt/elastalert-server/node_modules/object-resolve-path/object-resolve-path.js:13:11)
cdf60ab0f7d4_praeco_elastalert_1 |         at ServerConfig.get (/opt/elastalert-server/src/common/config/server_config.js:32:12)
cdf60ab0f7d4_praeco_elastalert_1 |         at /opt/elastalert-server/src/elastalert_server.js:84:58
cdf60ab0f7d4_praeco_elastalert_1 |         at /opt/elastalert-server/src/common/config/server_config.js:60:9
cdf60ab0f7d4_praeco_elastalert_1 |         at Array.forEach (<anonymous>)
cdf60ab0f7d4_praeco_elastalert_1 |         at /opt/elastalert-server/src/common/config/server_config.js:59:22
cdf60ab0f7d4_praeco_elastalert_1 | 04:24:35.215Z  INFO elastalert-server: Server:  Stopping server
cdf60ab0f7d4_praeco_elastalert_1 | /opt/elastalert-server/src/common/websocket.js:34
cdf60ab0f7d4_praeco_elastalert_1 |   wss.clients.forEach(function (ws) {
cdf60ab0f7d4_praeco_elastalert_1 |       ^
cdf60ab0f7d4_praeco_elastalert_1 |
cdf60ab0f7d4_praeco_elastalert_1 | TypeError: Cannot read property 'clients' of null
cdf60ab0f7d4_praeco_elastalert_1 |     at Timeout._onTimeout (/opt/elastalert-server/src/common/websocket.js:22:7)
cdf60ab0f7d4_praeco_elastalert_1 |     at listOnTimeout (internal/timers.js:531:17)
cdf60ab0f7d4_praeco_elastalert_1 |     at processTimers (internal/timers.js:475:7)
cdf60ab0f7d4_praeco_elastalert_1 exited with code 0

I'm running Elasticsearch 7.0.1.

**Comment by johnsusek** [comment]
Hi thanks for the report. Unfortunately ES7 is not supported yet. Elastalert has it in a beta branch but has not released ES7 support for their main master branch. Once that hits master I will make any changes as needed for praeco. This is actually tracked in #132, so closing this as a dupe.

**Comment by singhabhi786** [comment]
Hi John,
When i am deploying praeco, it is throwing :
API error
Error: Request failed with status code 500
Note: I have ran my elastalert server as a container and i can access it at localhost:3030.

**Comment by singhabhi786** [comment]
Sorry, little modification in the previous comment, post deployment, while accessing i am getting error.
I have provided the path and es host in the config files.
