### ISSUE TITLE
Slack Channel is required even when slack is not selected as an Alert Method

### ISSUE THREAD

**Issue by surfer190** [ServerCentral/praeco#141]
With just selecting HTTP Post as the method the slack channel is also required

<img width="428" alt="Screen Shot 2019-06-14 at 14 42 22" src="https://user-images.githubusercontent.com/3285222/59510165-4fc34c00-8eb3-11e9-87b8-4c90f2465a27.png">

Then you have to fill out the channel and have slack selected otherwise it will not save

<img width="1082" alt="Screen Shot 2019-06-14 at 14 42 11" src="https://user-images.githubusercontent.com/3285222/59510230-7aada000-8eb3-11e9-8348-5746b46cc142.png">

**Comment by johnsusek** [comment]
Hi thanks for the report, will take a look soon

**Comment by johnsusek** [comment]
okay this is fixed, there was some wonky behavior with the way those tabs got enabled/disabled as you were choosing alert desintations. will be in the next release
