### ISSUE TITLE
Failure to parse mapping if no properties are present

### ISSUE THREAD

**Issue by alexpanas** [ServerCentral/praeco#144]
Hello,

As far as I can see -  the code in elasticSearchMetadata.js fails in case one of the mapping types of an index not having "properties" field in it and results in

> "Get mapping failed. Make sure the index exists.
> Could not fetch mappings." 

error.

According to https://www.elastic.co/guide/en/elasticsearch/reference/current/properties.html
Properties can be added dynamically just by indexing documents containing new fields.

So 
```
 "mappings": {
      "_default_": {
        "_source": {
          "excludes": [
            "@type",
            "@sequence"
          ]
        },
        "dynamic_templates": [
          {
            "message_field": {
              "match": "message",
              "match_mapping_type": "string",
              "mapping": {
                "doc_values": false,
                "fielddata": false,
                "type": "text"
              }
            }
          }
        ]
      }

```
Is valid for a new index that has not had any documents added yet for example, or if you have multiple mapping types - and only one is actually being used.
If any property is added - praeco starts working.

The template:
```

"mappings": {
      "_default_": {
        "_source": {
          "excludes": [
            "@type",
            "@sequence"
          ]
        },
        "dynamic_templates": [
          {
            "message_field": {
              "match": "message",
              "match_mapping_type": "string",
              "mapping": {
                "doc_values": false,
                "fielddata": false,
                "type": "text"
              }
            }
          }
        ],
		 "properties": {
          "test_property": {
            "type": "date"
          }
      }
```
appears to be working.

**Comment by alexpanas** [comment]
Basically a simple check to ensure that we proceed only if mp.propertis exist should be enough to fix the issue - something like 
`export function buildMappingFields(mapping) {
  let fields = {};
  Object.values(mapping)
    .map(m => m.mappings)
    .forEach(mping => {
      Object.values(mping).forEach(mp => {
        if (typeof mp.properties !== 'undefined') {
          Object.entries(mp.properties).forEach(prop => {
            let name = prop[0];
            let field = fields[name];
            let value = prop[1];

            if (field) {
            // this field already exists in our mapping,
            // merge in extra fields (.raw, .keyword)
            // if they exist
              if (value.fields) {
                Object.entries(value.fields).forEach(([vfName, vfValue]) => {
                // vfName will be something like 'raw'
                  if (!field.fields) field.fields = {};
                  field.fields[vfName] = vfValue;
                });
              }
            } else {
              fields[name] = value;
            }
          });
        }
      });
    });

  return fields;
}
`

**Comment by johnsusek** [comment]
Thanks for the report, will take a look soon!

**Comment by johnsusek** [comment]
Ok I've added that check, fix will go out in next release
