### ISSUE TITLE
Issue while sending http post alert

### ISSUE THREAD

**Issue by mukeshchouhan** [ServerCentral/praeco#146]
I am getting below error while posting alert to API via http post alert-

`ERROR:root:Error while running alert http_post: Error posting HTTP Post alert: 407 Client Error: authenticationrequired for url: <my api url>`

I am able to post the json on my URL through curl command.

**Comment by johnsusek** [comment]
Your receiving API endpoint requires authentication which the http post alert doesn't support. I would set up a new endpoint for praeco without authentication that does whatever work is required to process your results.

**Comment by mukeshchouhan** [comment]
I want to add below for http post alert-

http_post_headers:
  content-type: 'application/json'

**Comment by nsano-rururu** [comment]
@mukeshchouhan

For settings that cannot be set on the screen, write them in rules / BaseRule.config.
