### ISSUE TITLE
Add Jira support

### ISSUE THREAD

**Issue by osherdp** [ServerCentral/praeco#147]
Hi, 

We want very much to use praeco in our organization.
The major thing we lack in praeco is the ability to open Jira issues. 
Is it planned to add it soon?

**Comment by phil21** [comment]
I don't believe we ever considered this.  As a workaround you could setup an e-mail address for the Jira mail handler, and setup e-mail alerts.

@johnsusek will have to see how difficult adding this alert type would be to the UI itself.

**Comment by osherdp** [comment]
Issue done
