### ISSUE TITLE
Not all alerts are being sent when testing a rule 

### ISSUE THREAD

**Issue by osherdp** [ServerCentral/praeco#152]
When applying a flatline rule & using the test feature, the second alert fails to be sent:
```
ERROR:root:Traceback (most recent call last):
  File "/ope/elastalert/elastalert/elastalert.py", line 1440, in alert
    return self.send_alert(matches, rule, alert_time=alert_time, retried=retried)
  File "/ope/elastalert/elastalert/elastalert.py" line 1543, in send_alert
    self.thread_data.alerts_sent += 1
AttributeError: '_thread._local' object has no attribute 'alerts_sent'
```

It doesn't seem to happen when enabling the rule regularly.

A complete reproduction steps:
* Make a rule that can happen at least two times (I use flatline to make it available without having to use any data)
* Test it for a short period of time
* The first email should be sent, the second wouldn't and should send the error to praeco

**Comment by johnsusek** [comment]
Yes, can you please file this with https://github.com/Yelp/elastalert? Make sure to provide them with the .yaml for your rule. 

Thanks!

**Comment by daichi703n** [comment]
@osherdp @surfer190 
This issue will be fixed with this 2 bugfixes. Please refer below.

https://github.com/Yelp/elastalert/issues/2556

https://github.com/Yelp/elastalert/issues/2600
https://github.com/Yelp/elastalert/commit/cfa98a12bb7739cfc21a16a418fe95375277f1fd
