### ISSUE TITLE
0.4.4 "enabled by default" fix is missing ConfigBuilder.vue change

### ISSUE THREAD

**Issue by osherdp** [ServerCentral/praeco#153]
Hey
The 0.4.4 "Enable rules by default" to avoid the APscheduler problem is missing a change to the ConfigBuilder.vue file - Line 105.
      this.$store.commit('config/settings/UPDATE_ENABLED', false); 
the parameters should be changed to true
After we modified it in our local machine, it worked flawlessly

P.S  We are huge fan of your work, if you have a beerpay account or something similar, let us know!

**Comment by johnsusek** [comment]
Oops, just put out a new release to fix this, thanks!
