### ISSUE TITLE
 Rule not found, it may have been moved or deleted.

### ISSUE THREAD

**Issue by vistrate** [ServerCentral/praeco#157]
Hi,

I can not save my alert during its creation ?

Has anyone would have a tip to solve it ?

**Comment by kklemen** [comment]
Upgraded to praeco 14? There was a bug in previous versions.

**Comment by vistrate** [comment]
Hi @kklemen this the same, even after upgrading.

**Comment by vistrate** [comment]
I have resolved the trouble by following this other post:
https://github.com/bitsensor/elastalert/issues/101

It is needed to stop the docker instance and give the adequate rights to rules and rule_templates.
`chmod -R 777 rules rule_templates`
