### ISSUE TITLE
Create a service with Praeco

### ISSUE THREAD

**Issue by vistrate** [ServerCentral/praeco#158]
Hi everyone,

I try to create a service with systemd on ubuntu for Praeco, there is my code:
`[Unit]
Description=Praeco Service
After=praeco.service

[Service]
Type=Simple
WorkingDirectory=/opt/praeco
ExecStart=/usr/bin/docker-compose --file /opt/praeco/docker-compose.yml up
Group=root
User=root
StandardOutput=syslog
StandardError=syslog
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target
`

But that does not work. Does anyone add an idea to resolve that ?

Thanks for advance

**Comment by vistrate** [comment]
I have just found how to do:
1/ create and give the adequate right to the systemd configuration:
`touch /etc/systemd/system/praeco.service
chmod 644 /etc/systemd/system/praeco.service`

2/ edit praeco.service and add the following lines:
`
[Unit]
Description=Praeco Service
After=praeco.service

[Service]
Type=Simple
WorkingDirectory=/opt/praeco
ExecStart=/usr/bin/docker-compose --file /opt/praeco/docker-compose.yml up
ExecStop=/usr/bin/docker-compose --file /opt/praeco/docker-compose.yml down
StandardOutput=file:/var/log/praeco.log
Group=root
User=root
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target`

3/ Afterward, edit /opt/praeco/docker-compose.yml and comment these lines:
`    #extra_hosts:
     # - 'elasticsearch:${PRAECO_ELASTICSEARCH}'`
and add this line embedded into :
`services:
  elastalert:
        environment:
        - PRAECO_ELASTICSEARCH=IP address of ELK`

4/ `systemctl daemon-reload`

To consult the logs go to : 
/var/log/praeco.log

**Comment by ck-7** [comment]
Without docker create systemd for praeco ?
