### ISSUE TITLE
Release docker images with concrete tags instead of 'latest'

### ISSUE THREAD

**Issue by osherdp** [ServerCentral/praeco#166]
Hi,

I wanted to know if it's possible releasing the docker images of praeco with the actual versions, e.g. 0.4.5, 1.0.0, etc... That's instead of always releasing with the version tag of 'latest'.

It will enable a more explicit usage and allow downgrading in case of bugs.

**Comment by amerinoo** [comment]
I'm on support of @osherdp comment, tags would be very very useful for everybody!

**Comment by johnsusek** [comment]
100% agreed. When I started this my understanding of docker wasn't too deep. Now I see how tagging releases is useful. I might also start linking to the docker image with each release. Thx @osherdp and @amerinoo

**Comment by johnsusek** [comment]
Closing - will tag docker releases going forward
