### ISSUE TITLE
How to create index?

### ISSUE THREAD

**Issue by brdhunga** [ServerCentral/praeco#169]
I have been getting errors that the following indexes were not found. 

praeco_elastalert_status
praeco_elastalert_alertas
praeco_elastalert_status_status

How do I create these? thanks

**Comment by johnsusek** [comment]
These should be created the first time you run elastalert. Can you post the exact errors you are seeing?

**Comment by brdhunga** [comment]
Turns out, I had put incorrect authentication info. All is good !!
