### ISSUE TITLE
Connect Elastalert to Elasticsearch cluster

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#172]
How can I connect Elastalert to an Elasticsearch cluster?.
Currently the configuration allows us to connect to only one node. I have a multi-node cluster and if do connect to only one node, what happens if that node goes down?.
So is there a way to connect to a multi-node cluster from Elastalert?

**Comment by johnsusek** [comment]
This is more of a question for https://github.com/Yelp/elastalert, please check in there. Thanks!
