### ISSUE TITLE
praeco shows in WebUI "praeco 0.4.5" instead of 1.0

### ISSUE THREAD

**Issue by StefanSa** [ServerCentral/praeco#174]
Hi,
First of all, thank you for working with praeco.
praeco shows in WebUI "praeco 0.4.5" instead of 1.0.
![v1](https://user-images.githubusercontent.com/6105075/67942217-a8338580-fbd7-11e9-97ba-5b0abbeb1520.png)
a git pull, however, says "Already up-to-date"

**Comment by johnsusek** [comment]
If you try the upgrade commands:

```
docker pull servercentral/praeco; docker pull servercentral/elastalert
docker-compose up --force-recreate --build; docker image prune -f
```

Does that help?

**Comment by StefanSa** [comment]
hi john,
that does not help either, here too the images are up-to-date.
`
 docker pull servercentral/praeco; docker pull servercentral/elastalert
Using default tag: latest
Trying to pull repository docker.io/servercentral/praeco ... 
latest: Pulling from docker.io/servercentral/praeco
Digest: sha256:5b818aba062bcbf27a18d0f0d27cb4d67056f772d750edcbb5889098a531a222
Status: Image is up to date for docker.io/servercentral/praeco:latest
Using default tag: latest
Trying to pull repository docker.io/servercentral/elastalert ... 
latest: Pulling from docker.io/servercentral/elastalert
Digest: sha256:7c42b9eefe249112dd16387b12d0f0234946c3386908174a28454b5dbd6864fd
Status: Image is up to date for docker.io/servercentral/elastalert:latest
[root@logger praeco]# docker-compose up --force-recreate --build; docker image prune -f
`

**Comment by StefanSa** [comment]
Hi john,
any news here ?
I also missing in ruletypes "spike".

**Comment by johnsusek** [comment]
Hello, can you try to update again and see if that helps?

**Comment by StefanSa** [comment]
John, thanks
Perfect, that seems with the version problem fixed. But how do i create a "spike" rule?
Also, the template folder is empty (no examples), but that's not the main problem.
![Rules](https://user-images.githubusercontent.com/6105075/68416167-3be6f200-0194-11ea-8003-aaf3fd2d35af.PNG)

**Comment by johnsusek** [comment]
You want to use "WHEN count" and then click "IS" and there is a spike option: 
![Screen Shot 2019-11-07 at 12 32 37 PM](https://user-images.githubusercontent.com/611996/68416770-c01c8380-015a-11ea-9ebc-505aa9dc289b.png)

**Comment by StefanSa** [comment]
john
you're right, with "count", i can create spikes rules, but with agg? see example
```name: CPU usgae
type: metric_aggregation
index: metricbeat-*
buffer_time:
  minutes: 10
metric_agg_key: system.cpu.total.pct
metric_agg_type: avg
query_key: beat.hostname
doc_type: doc
bucket_interval:
  minutes: 5
sync_bucket_interval: true
max_threshold: 0.6
filter:
- term:
    metricset.name: cpu
alert:
- "email"
email:
- "xyz@xy.com"
```
