### ISSUE TITLE
Not able to create alert rules in praeco ui

### ISSUE THREAD

**Issue by suresh447** [ServerCentral/praeco#186]
Hi,

I am not able to create alert rules in praeco UI.Please find the details how i trying to add rules

![image](https://user-images.githubusercontent.com/33586664/74714402-7b6fb080-5250-11ea-9e76-dc29914f62fd.png)

![image](https://user-images.githubusercontent.com/33586664/74714416-84608200-5250-11ea-949e-a31ce0fc5a45.png)

After giving all the deatils it is giving me the error 

![image](https://user-images.githubusercontent.com/33586664/74714470-9b9f6f80-5250-11ea-896d-38121c34d4a7.png)

Please help me how to sort out this

**Comment by daichi703n** [comment]
Hi, @suresh447 
Did you create `rules/BaseRule.config` ?
I reproduce the warning message `Error saving config, are all fields filled out?` with NO `BaseRule.config`.

**Comment by suresh447** [comment]
Hi daichi,

I have modify rules/BaseRule.config with below lines
smtp_host: 'myhostname'
smtp_port: 587
smtp_ssl: 'false'
smtp_auth_file: '/home/ctpadmin/elastalert/auth_file.yml'

but still i am facing Error saving config, are all fields filled out?
and also elastalert-server is throwing error like

13:15:57.700Z ERROR elastalert-server:
    TestController:  Failed to test rule with error: Traceback (most recent call last):
      File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/ctpadmin/elastalert/elastalert/test_rule.py", line 13, in <module>
        import mock
      File "/home/ctpadmin/.local/lib/python3.5/site-packages/mock/__init__.py", line 7, in <module>
        import mock.mock as _mock
      File "/home/ctpadmin/.local/lib/python3.5/site-packages/mock/mock.py", line 765
        mock_name = f'{self._extract_mock_name()}.{name}'
                                                        ^
    SyntaxError: invalid syntax

**Comment by daichi703n** [comment]
Is the absolute path of `BaseRule.config` `/home/ctpadmin/elastalert/rules/BaseRule.config`? 

Could you tell me your directory layout of ElasrAlert, ElastAlert Server, Praeco?
And how are you running ElastAlert? `git clone`? `pip install`?
Released ElastAlert v2.0.1 (when using `pip install`) has issue about importing `BaseRule.config` and test run will be failed.

**Comment by suresh447** [comment]
No absolute path for BaseRule.config is /home/ctpadmin/praeco/rules/BaseRule.config

Directory Layout of Elastalert is 
ctpadmin@mgt-prd-prom:~/elastalert$ ll
total 172
drwxrwxr-x 13 ctpadmin ctpadmin  4096 Feb 19 05:58 ./
drwxr-xr-x 14 ctpadmin ctpadmin  4096 Feb 19 06:10 ../
-rw-r--r--  1 root     root        37 Jan 13 10:19 auth_file.yml
drwxr-xr-x  4 root     root      4096 Jan 13 06:52 build/
-rw-rw-r--  1 ctpadmin ctpadmin 10994 Jan 13 06:17 changelog.md
-rw-r--r--  1 ctpadmin ctpadmin  3302 Feb 13 06:41 config.yaml
-rw-rw-r--  1 ctpadmin ctpadmin  3321 Jan 13 07:07 config.yaml.example
drwxr-xr-x  2 root     root      4096 Jan 13 06:52 dist/
-rw-rw-r--  1 ctpadmin ctpadmin   261 Jan 13 06:17 docker-compose.yml
-rw-rw-r--  1 ctpadmin ctpadmin   244 Jan 13 06:17 Dockerfile-test
drwxrwxr-x  3 ctpadmin ctpadmin  4096 Jan 13 06:17 docs/
-rw-rw-r--  1 ctpadmin ctpadmin   216 Jan 13 06:17 .editorconfig
drwxrwxr-x  4 ctpadmin ctpadmin  4096 Jan 17 12:06 elastalert/
-rw-rw-r--  1 ctpadmin ctpadmin  7005 Feb 19 05:58 elastalertdirectorylayout.txt
drwxr-xr-x  2 root     root      4096 Jan 13 06:52 elastalert.egg-info/
drwxrwxr-x  2 ctpadmin ctpadmin  4096 Jan 17 13:11 example_rules/
drwxrwxr-x  8 ctpadmin ctpadmin  4096 Jan 13 06:17 .git/
-rw-rw-r--  1 ctpadmin ctpadmin   160 Jan 13 06:17 .gitignore
-rw-rw-r--  1 ctpadmin ctpadmin 11359 Jan 13 06:17 LICENSE
-rw-rw-r--  1 ctpadmin ctpadmin   528 Jan 13 06:17 Makefile
-rw-rw-r--  1 ctpadmin ctpadmin   718 Jan 13 06:17 .pre-commit-config.yaml
-rw-rw-r--  1 ctpadmin ctpadmin    74 Jan 13 06:17 pytest.ini
-rw-rw-r--  1 ctpadmin ctpadmin 16187 Jan 13 06:17 README.md
-rw-rw-r--  1 ctpadmin ctpadmin   114 Jan 13 06:17 requirements-dev.txt
-rw-rw-r--  1 ctpadmin ctpadmin   428 Jan 13 06:17 requirements.txt
drwxrwxr-x  2 ctpadmin ctpadmin  4096 Feb 18 07:28 rules/
drwxrwxr-x  2 ctpadmin ctpadmin  4096 Feb  7 11:07 rule_templates/
-rw-rw-r--  1 ctpadmin ctpadmin   574 Jan 13 06:17 .secrets.baseline
drwxr-xr-x  3 root     root      4096 Feb 13 10:52 server_data/
-rw-rw-r--  1 ctpadmin ctpadmin   100 Jan 13 06:17 setup.cfg
-rw-rw-r--  1 ctpadmin ctpadmin  1720 Jan 13 06:17 setup.py
-rw-rw-r--  1 ctpadmin ctpadmin   780 Jan 13 06:17 supervisord.conf.example
drwxrwxr-x  2 ctpadmin ctpadmin  4096 Jan 13 06:17 tests/
-rw-rw-r--  1 ctpadmin ctpadmin   609 Jan 13 06:17 tox.ini
-rw-rw-r--  1 ctpadmin ctpadmin  1262 Jan 13 06:17 .travis.yml

Directory Layout for elastalert-server is 
ctpadmin@mgt-prd-prom:~/elastalert-server$ ll
total 736
drwxrwxr-x  11 ctpadmin ctpadmin   4096 Feb 19 06:00 ./
drwxr-xr-x  14 ctpadmin ctpadmin   4096 Feb 19 06:10 ../
-rw-rw-r--   1 ctpadmin ctpadmin     35 Feb  7 08:02 .babelrc
drwxrwxr-x   2 ctpadmin ctpadmin   4096 Feb 13 13:08 config/
-rw-rw-r--   1 ctpadmin ctpadmin   8107 Feb  7 08:02 CONTRIBUTING.md
-rw-rw-r--   1 ctpadmin ctpadmin   1696 Feb  7 08:02 Dockerfile
-rw-rw-r--   1 ctpadmin ctpadmin    117 Feb  7 08:02 .dockerignore
-rw-rw-r--   1 ctpadmin ctpadmin    236 Feb  7 08:02 .editorconfig
drwxrwxr-x   2 ctpadmin ctpadmin   4096 Feb  7 08:02 elastalert_modules/
-rw-rw-r--   1 ctpadmin ctpadmin 430666 Feb 19 06:00 elastalert-serverdirectorylayout.txt
-rw-rw-r--   1 ctpadmin ctpadmin      5 Feb  7 08:02 .eslintignore
-rw-rw-r--   1 ctpadmin ctpadmin    430 Feb  7 08:02 .eslintrc.json
drwxrwxr-x   8 ctpadmin ctpadmin   4096 Feb  7 08:02 .git/
-rw-rw-r--   1 ctpadmin ctpadmin   1340 Feb  7 08:02 .gitignore
-rw-rw-r--   1 ctpadmin ctpadmin   2671 Feb  7 08:02 .gitlab-ci.yml
-rw-rw-r--   1 ctpadmin ctpadmin     43 Feb  7 08:02 index.js
-rw-rw-r--   1 ctpadmin ctpadmin   1702 Feb  7 08:02 LICENSE.md
-rw-rw-r--   1 ctpadmin ctpadmin    253 Feb  7 08:02 Makefile
drwxr-xr-x 441 root     root      20480 Feb 18 16:18 node_modules/
-rw-rw-r--   1 ctpadmin ctpadmin   1201 Feb  7 08:02 .npmignore
-rw-rw-r--   1 ctpadmin ctpadmin      5 Feb  7 08:02 .nvmrc
-rw-rw-r--   1 ctpadmin ctpadmin   1513 Feb  7 08:02 package.json
-rw-r--r--   1 ctpadmin ctpadmin 172651 Feb  7 12:18 package-lock.json
-rw-rw-r--   1 ctpadmin ctpadmin  12678 Feb  7 08:02 README.md
drwxrwxr-x   2 ctpadmin ctpadmin   4096 Feb  7 08:02 rule_templates/
drwxrwxr-x   2 ctpadmin ctpadmin   4096 Feb  7 08:02 scripts/
drwxrwxr-x   6 ctpadmin ctpadmin   4096 Feb  7 08:02 src/
drwxrwxr-x   2 ctpadmin ctpadmin   4096 Feb  7 08:02 test/
drwxrwxr-x   2 ctpadmin ctpadmin   4096 Feb  7 08:02 .vscode/

Directory Layout of Praeco is
ctpadmin@mgt-prd-prom:~/praeco$ ll
total 1140
drwxrwxr-x   10 ctpadmin ctpadmin   4096 Feb 19 06:10 ./
drwxr-xr-x   14 ctpadmin ctpadmin   4096 Feb 19 06:10 ../
-rw-rw-r--    1 ctpadmin ctpadmin     84 Feb 13 11:22 babel.config.js
-rw-rw-r--    1 ctpadmin ctpadmin     33 Feb 13 11:22 .browserslistrc
drwxrwxr-x    2 ctpadmin ctpadmin   4096 Feb 13 12:56 config/
-rw-rw-r--    1 ctpadmin ctpadmin    339 Feb 13 11:22 CREDITS.TXT
-rw-rw-r--    1 ctpadmin ctpadmin     50 Feb 13 11:22 cypress.json
-rw-rw-r--    1 ctpadmin ctpadmin    721 Feb 13 11:22 docker-compose.yml
-rw-rw-r--    1 ctpadmin ctpadmin   1009 Feb 13 11:22 Dockerfile
-rw-rw-r--    1 ctpadmin ctpadmin     37 Feb 13 11:22 .dockerignore
-rw-rw-r--    1 ctpadmin ctpadmin   1028 Feb 13 11:22 .drone.yml
-rw-rw-r--    1 ctpadmin ctpadmin   1476 Feb 13 11:22 .eslintrc.js
drwxrwxr-x    8 ctpadmin ctpadmin   4096 Feb 13 11:22 .git/
-rw-rw-r--    1 ctpadmin ctpadmin    281 Feb 13 11:22 .gitignore
-rw-rw-r--    1 ctpadmin ctpadmin  35149 Feb 13 11:22 LICENSE
-rw-rw-r--    1 ctpadmin ctpadmin    408 Feb 13 11:22 MAINTENANCE.md
drwxrwxr-x    2 ctpadmin ctpadmin   4096 Feb 13 11:22 nginx_config/
drwxr-xr-x 1001 ctpadmin ctpadmin  36864 Feb 18 16:21 node_modules/
-rw-rw-r--    1 ctpadmin ctpadmin   3208 Feb 13 11:22 package.json
-rw-rw-r--    1 ctpadmin ctpadmin 970951 Feb 13 11:25 package-lock.json
-rw-rw-r--    1 ctpadmin ctpadmin     62 Feb 13 11:22 postcss.config.js
drwxrwxr-x    3 ctpadmin ctpadmin   4096 Feb 13 12:00 public/
-rw-rw-r--    1 ctpadmin ctpadmin   9891 Feb 13 11:22 README.md
drwxrwxr-x    2 ctpadmin ctpadmin   4096 Feb 18 13:24 rules/
-rwxrwxr-x    1 ctpadmin ctpadmin    784 Feb 13 11:22 run_tests.sh*
drwxrwxr-x    8 ctpadmin ctpadmin   4096 Feb 13 11:22 src/
drwxrwxr-x    4 ctpadmin ctpadmin   4096 Feb 13 11:22 tests/
-rw-rw-r--    1 ctpadmin ctpadmin   1772 Feb 13 11:22 UPGRADING.md
-rw-rw-r--    1 ctpadmin ctpadmin   1500 Feb 13 11:22 vue.config.js

And i am running Elastalert as background service with the below file from the location /lib/systemd/system/elastalert.service 
[Unit]
Description=Elastalert
After=elasticsearch.service

[Service]
Type=simple
Restart=on-failure
WorkingDirectory=/home/ctpadmin/elastalert
ExecStart=/usr/local/bin/elastalert

[Install]
WantedBy=multi-user.target

**Comment by daichi703n** [comment]
Thanks. I figured out your miss settings.

Please copy your `/home/ctpadmin/praeco/rules/BaseRule.config` into `/home/ctpadmin/elastalert/rules/`.

`BaseRule.config` should be placed on `elastalert` directory.

And please note, in `elastalert-server/config/config.json`, you have to modify `elastalertPath` from default.

```
{
  ...
  "elastalertPath": "/home/ctpadmin/elastalert",
  ...
}
```

default is `/opt/elastalert`. not match your env.

**Comment by suresh447** [comment]
I already made all these changes but still facing same error "Error saving config, are all fields filled out?" while saving the rule in praeco gui

![image](https://user-images.githubusercontent.com/33586664/74812307-43807000-5319-11ea-9adc-a9bd364fb820.png)

**Comment by suresh447** [comment]
I am also getting the error from elastalert-server

07:40:43.779Z ERROR elastalert-server:
    TestController:  Failed to test rule with error: Traceback (most recent call last):
      File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/ctpadmin/elastalert/elastalert/test_rule.py", line 13, in <module>
        import mock
      File "/home/ctpadmin/.local/lib/python3.5/site-packages/mock/__init__.py", line 7, in <module>
        import mock.mock as _mock
      File "/home/ctpadmin/.local/lib/python3.5/site-packages/mock/mock.py", line 765
        mock_name = f'{self._extract_mock_name()}.{name}'
                                                        ^
    SyntaxError: invalid syntax

**Comment by daichi703n** [comment]
Umm...
This seems to be issue on ElastAlert. (Sorry for skip comment to this log at first time...)
An error occured when ElastAlert Server hooks ElastAlert.

Would you please search ElastAlert issues same as your error? I also search.
https://github.com/Yelp/elastalert/issues

I only have Docker Praeco env. It is difficult to test in env like you. (e.g. Python version)

**Comment by suresh447** [comment]
Hi Daichi,
Can you please provide steps to install elastalert-server and praeco server using docker.

**Comment by daichi703n** [comment]
Official steps are:
```
git clone https://github.com/ServerCentral/praeco
cd praeco
export PRAECO_ELASTICSEARCH=<your elasticsearch ip>
docker-compose up
```
https://github.com/ServerCentral/praeco#quickstart

**But, now ElastAlert Docker Container has some bugs**, I fixed it on my repo. Please `git clone` from my repo.
```
git clone https://github.com/daichi703n/praeco
cd praeco
export PRAECO_ELASTICSEARCH=<your elasticsearch ip>
docker-compose up
```

Please modify these configs same as native installation.

```
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/api.config.json:/opt/elastalert-server/config/config.json
      - ./rules:/opt/elastalert/rules
    volumes:
      - ./public/praeco.config.json:/var/www/html/praeco.config.json
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
```

**Comment by daichi703n** [comment]
I tested on native install. Rule is successfully created. 
Docker CentOS7, Python3.5, latest source code.

I forgot to ask how each system(ElastAlert, ElastAlert Server, Praeco) did you install?

If you install ElastAlert with these steps,
https://elastalert.readthedocs.io/en/latest/running_elastalert.html#downloading-and-configuring
did you success to run `python setup.py install`?

On my env, some dependencies are not installed automatically. Did you complete to install each dependencies manually?

**Comment by suresh447** [comment]
I have installed ElastAlert,ElastAlertServer and Praeco on ubuntu 16.04.
ElastAlert Installation i followed https://elastalert.readthedocs.io/en/latest/running_elastalert.html#downloading-and-configuring with python3
ElastAlert-server Installation
git clone https://github.com/ServerCentral/elastalert-server.git
cd ~/elastalert-server
vi config/config.json
npm install
npm run start

Praeco installation
git clone https://github.com/ServerCentral/praeco.git
cd ~/praeco
npm install
export PRAECO_ELASTICSEARCH=<your elasticsearch ip>
npm run serve

Yes i succussfully run the command using python3 setup.py install

**Comment by daichi703n** [comment]
Umm... I think no problem.
What is your default `python` version? Check with `python --version`. Is it 3.5? OS default 2.x not installed?

Did you restart each service after modify config? (I think of course you did...)

**Comment by suresh447** [comment]
yes i have installed python3.5 default python 2.x not installed.
Yes i have restarted each service.

**Comment by daichi703n** [comment]
On my testing in ubuntu16.04, I succeeded to reproduce the issue.

Test running `pip3 install elastalert` failed with this log:

```
ERROR: Package 'mock' requires a different Python: 3.5.2 not in '>=3.6'
```

**mock** is root cause of your error. It seems not to be compatible with python 3.5. (maybe...)
Could you update python?

BTW, could you run with docker?

**Comment by daichi703n** [comment]
If using Python 3.6, ploblem was solved and I can save rule successfully.

```
root@339e332e7e10:/# python3 --version
Python 3.6.10
```

**Comment by suresh447** [comment]
i have updated python version from 3.5.2 to 3.6.10
Now again i need to install elastalert with the updated python version?

**Comment by daichi703n** [comment]
Thanks.
I think so, new `/home/ctpadmin/.local/lib/python3.6/site-packages` have to be installed. I'm sorry, but I'm not very familiar with how Python packages work...

**Comment by suresh447** [comment]
I tried to run praeco using your docker compose file but it is throwing error

Traceback (most recent call last):
elastalert_1  |       File "/home/node/.local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 124, in perform_request
elastalert_1  |         response = self.session.send(prepared_request, **send_kwargs)
elastalert_1  |       File "/home/node/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
elastalert_1  |         r = adapter.send(request, **kwargs)
elastalert_1  |       File "/home/node/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
elastalert_1  |         raise ConnectionError(e, request=request)
elastalert_1  |     requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88bc954128>: Failed to establish a new connection: [Errno 111] Connection refused',))

my elasticsearch is running on my private ip but it is taking localhost where i need to keep private ip instaed of localhost

**Comment by daichi703n** [comment]
Please set your `es_host`, etc. in 

`config/elastalert.yaml`: ElastAlert’s `config.yaml`

`config/api.config.json`: ElastAlert Server’s `config.json`

and run `docker-compose up` or `docker-compose restart`.

**Comment by suresh447** [comment]
Can you please help me how to modify these files

i tried to enter into containers with this command 
docker exec -it cc281a51e7fe /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown 

Can you please tell me how to login to elastalert container and praeco container to modify the config files

**Comment by daichi703n** [comment]
You don’t have to enter into container. The files will be mounted from Docker host to container. Therefore, you can modify config files on the host directly.

```
git clone https://github.com/daichi703n/praeco
cd praeco
vi config/elastalert.yaml
vi config/api.config.json
export PRAECO_ELASTICSEARCH=<your elasticsearch ip>
docker-compose up
```

**Comment by suresh447** [comment]
I really thanks for your support.

Now i am able to save the alerts and i am facing other issue i am not able receive alerts i gave SMTP settings in BaseRuleconfig file
smtp_host: '30.18.0.101'
smtp_port: 587
smtp_ssl: 'false'
smtp_auth_file: '/home/ctpadmin/docker/praeco/auth_file.yml'

ERROR elastalert-server:
0379f77eb433_praeco_elastalert_1 |     ProcessController:  Traceback (most recent call last):
0379f77eb433_praeco_elastalert_1 |       File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
0379f77eb433_praeco_elastalert_1 |         "__main__", mod_spec)
0379f77eb433_praeco_elastalert_1 |       File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
0379f77eb433_praeco_elastalert_1 |         exec(code, run_globals)
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/elastalert.py", line 2097, in <module>
0379f77eb433_praeco_elastalert_1 |         sys.exit(main(sys.argv[1:]))
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/elastalert.py", line 2091, in main
0379f77eb433_praeco_elastalert_1 |         client = ElastAlerter(args)
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/elastalert.py", line 140, in __init__
0379f77eb433_praeco_elastalert_1 |         self.rules = self.rules_loader.load(self.conf, self.args)
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/loaders.py", line 114, in load
0379f77eb433_praeco_elastalert_1 |         rule = self.load_configuration(rule_file, conf, args)
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/loaders.py", line 217, in load_configuration
0379f77eb433_praeco_elastalert_1 |         self.load_modules(rule, args)
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/loaders.py", line 475, in load_modules
0379f77eb433_praeco_elastalert_1 |         rule['alert'] = self.load_alerts(rule, alert_field=rule['alert'])
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/loaders.py", line 508, in load_alerts
0379f77eb433_praeco_elastalert_1 |         alert_field = [create_alert(a, b) for a, b in alert_field]
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/loaders.py", line 508, in <listcomp>
0379f77eb433_praeco_elastalert_1 |         alert_field = [create_alert(a, b) for a, b in alert_field]
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/loaders.py", line 499, in create_alert
0379f77eb433_praeco_elastalert_1 |         return alert_class(alert_config)
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/alerts.py", line 418, in __init__
0379f77eb433_praeco_elastalert_1 |         self.get_account(self.rule['smtp_auth_file'])
0379f77eb433_praeco_elastalert_1 |       File "/opt/elastalert/elastalert/alerts.py", line 314, in get_account
0379f77eb433_praeco_elastalert_1 |         account_conf = yaml_loader(account_file_path)
0379f77eb433_praeco_elastalert_1 |       File "/home/node/.local/lib/python3.6/site-packages/staticconf/loader.py", line 167, in yaml_loader
0379f77eb433_praeco_elastalert_1 |         with open(filename) as fh:
0379f77eb433_praeco_elastalert_1 |     FileNotFoundError: [Errno 2] No such file or directory: '/home/ctpadmin/docker/praeco/auth_file.yml'
0379f77eb433_praeco_elastalert_1 |
0379f77eb433_praeco_elastalert_1 | 14:15:21.268Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
Connection reset by 23.96.86.199 port 22

**Comment by daichi703n** [comment]
Great!!

You have to mount `auth_file.yml` to container. Copy your file to `data/elastalert/config/`. And add this line to `docker-compose.yml`

```
    - "./data/elastalert/config/auth_file.yml:/opt/elastalert/config/auth_file.yml"
```

like below.

```
  elastalert:
    image: servercentral/elastalert
    ports:
    - "3030:3030"
    - "3333:3333"
    volumes:
    - "./data/elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml"
    - "./data/elastalert/config/ca.crt:/opt/elastalert/config/ca.crt"
    - "./data/elastalert/config/auth_file.yml:/opt/elastalert/config/auth_file.yml"
    - "./data/elastalert/config/api.config.json:/opt/elastalert-server/config/config.json"
    - "./data/elastalert/rules:/opt/elastalert/rules"
    - "./data/elastalert/rule_templates:/opt/elastalert/rule_templates"
```

Fix your `auth_file.yml` path in `BaseRule.config` to `/opt/elastalert/config/auth_file.yml` (path in ther container).

**Comment by suresh447** [comment]
After saving alert it is giving 

![image](https://user-images.githubusercontent.com/33586664/75038703-ecc39380-54dc-11ea-997b-dc034eccbe42.png)

API error
Error: Request failed with status code 400

**Comment by suresh447** [comment]
It was my fault daichi i gave '%' in the name of alert that's why it is giving 400 error.

**Comment by daichi703n** [comment]
It was good that it started without any problems. 👍
Do you have more question?
If not, please close this issue.

**Comment by suresh447** [comment]
Hi daichi 
I have added  my auth_file location in docker composefile "./data/elastalert/config/auth_file.yml:/opt/elastalert/config/auth_file.yml" and also added this path in auth_file.yml path in BaseRule.config to /opt/elastalert/config/auth_file.yml (path in the container).
Still it is throwing error like

 ERROR elastalert-server:
elastalert_1  |     ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
elastalert_1  |         "__main__", mod_spec)
elastalert_1  |       File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 2097, in <module>
elastalert_1  |         sys.exit(main(sys.argv[1:]))
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 2091, in main
elastalert_1  |         client = ElastAlerter(args)
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 140, in __init__
elastalert_1  |         self.rules = self.rules_loader.load(self.conf, self.args)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 114, in load
elastalert_1  |         rule = self.load_configuration(rule_file, conf, args)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 217, in load_configuration
elastalert_1  |         self.load_modules(rule, args)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 475, in load_modules
elastalert_1  |         rule['alert'] = self.load_alerts(rule, alert_field=rule['alert'])
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 508, in load_alerts
elastalert_1  |         alert_field = [create_alert(a, b) for a, b in alert_field]
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 508, in <listcomp>
elastalert_1  |         alert_field = [create_alert(a, b) for a, b in alert_field]
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 499, in create_alert
elastalert_1  |         return alert_class(alert_config)
elastalert_1  |       File "/opt/elastalert/elastalert/alerts.py", line 418, in __init__
elastalert_1  |         self.get_account(self.rule['smtp_auth_file'])
elastalert_1  |       File "/opt/elastalert/elastalert/alerts.py", line 314, in get_account
elastalert_1  |         account_conf = yaml_loader(account_file_path)
elastalert_1  |       File "/home/node/.local/lib/python3.6/site-packages/staticconf/loader.py", line 167, in yaml_loader
elastalert_1  |         with open(filename) as fh:
elastalert_1  |     IsADirectoryError: [Errno 21] Is a directory: '/opt/elastalert/auth_file.yml'
elastalert_1  |
elastalert_1  | 06:54:33.961Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1
Can you please help me on this.

**Comment by suresh447** [comment]
Hi daichi
I have added my auth_file location in docker composefile "./data/elastalert/config/auth_file.yml:/opt/elastalert/config/auth_file.yml" and also added this path in auth_file.yml path in BaseRule.config to /opt/elastalert/config/auth_file.yml (path in the container).
Still it is throwing error like

ProcessController:  Traceback (most recent call last):
elastalert_1  |       File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
elastalert_1  |         "__main__", mod_spec)
elastalert_1  |       File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
elastalert_1  |         exec(code, run_globals)
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 2097, in <module>
elastalert_1  |         sys.exit(main(sys.argv[1:]))
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 2091, in main
elastalert_1  |         client = ElastAlerter(args)
elastalert_1  |       File "/opt/elastalert/elastalert/elastalert.py", line 140, in __init__
elastalert_1  |         self.rules = self.rules_loader.load(self.conf, self.args)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 114, in load
elastalert_1  |         rule = self.load_configuration(rule_file, conf, args)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 217, in load_configuration
elastalert_1  |         self.load_modules(rule, args)
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 475, in load_modules
elastalert_1  |         rule['alert'] = self.load_alerts(rule, alert_field=rule['alert'])
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 508, in load_alerts
elastalert_1  |         alert_field = [create_alert(a, b) for a, b in alert_field]
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 508, in <listcomp>
elastalert_1  |         alert_field = [create_alert(a, b) for a, b in alert_field]
elastalert_1  |       File "/opt/elastalert/elastalert/loaders.py", line 499, in create_alert
elastalert_1  |         return alert_class(alert_config)
elastalert_1  |       File "/opt/elastalert/elastalert/alerts.py", line 418, in __init__
elastalert_1  |         self.get_account(self.rule['smtp_auth_file'])
elastalert_1  |       File "/opt/elastalert/elastalert/alerts.py", line 314, in get_account
elastalert_1  |         account_conf = yaml_loader(account_file_path)
elastalert_1  |       File "/home/node/.local/lib/python3.6/site-packages/staticconf/loader.py", line 167, in yaml_loader
elastalert_1  |         with open(filename) as fh:
elastalert_1  |     IsADirectoryError: [Errno 21] Is a directory: '/opt/elastalert/config/auth_file.yml'
elastalert_1  |
elastalert_1  | 06:54:33.961Z ERROR elastalert-server: ProcessController:  ElastAlert exited with code 1

**Comment by daichi703n** [comment]
`IsADirectoryError: [Errno 21] Is a directory: '/opt/elastalert/config/auth_file.yml'` is seemed to be occured by volumeMount issue.
When src file does not exist, dst path will be generated as directory (not file).

Is `./data/elastalert/config/auth_file.yml` placed properly?

**Comment by suresh447** [comment]
Thanks Daichi now i am able to successfully mount smtp_auth_file. But alerts are not triggered even though Test is running successfully

![image](https://user-images.githubusercontent.com/33586664/75143677-79f42b80-571b-11ea-970a-0441dd85dbe7.png)
 My smtp details is 
smtp_host: 'myhostname'
smtp_port: 587
smtp_ssl: 'false'
smtp_auth_file: '/opt/elastalert/authfile.yaml'

**Comment by daichi703n** [comment]
Do you have any error log? It is SMTP server conectivity ploblem.

Parameters for SMTPS & STARTTLS is here, I tested each patterns.
https://github.com/bosh-elastic-stack/elastalert-boshrelease/pull/5#issuecomment-490370028

With sendgrid, like your setting works for me.

**Comment by suresh447** [comment]
Not able to configure SMTP using Send Grid.Can you help me in praeco server integrate with Jira tool

**Comment by daichi703n** [comment]
Sorry... I've never used Jira with ElastAlert, Praeco...
Note that, Jira integration is provided by ElastAlert (not Praeco. Praeco only generates rules.yml). Please check how to set params for Jira integration on ElastAlert repo and docs.

**Comment by suresh447** [comment]
Thanks a Lot daichi for your valuable support that was really appreciate
Can you provide some input to create CPU and Memory utilization of VMs rules in praeco server. I created an alert for CPU and Memory with the help of fields like system.cpu.total.pct and system.memory.total.pct but it is not triggering the alerts even-though my smtp is working fine.

**Comment by suresh447** [comment]
Can you help me with some of sample rules for CPU/Memory/Disk alerts

**Comment by daichi703n** [comment]
It seems to be able to alert by `metrics_aggregation` rule, in Praeco, `max`, `average`, etc , isn't it?

![image](https://user-images.githubusercontent.com/22485636/75229541-792fc800-57f5-11ea-8171-1e0415565c9e.png)

https://elastalert.readthedocs.io/en/latest/ruletypes.html#metric-aggregation

But, I don't use Praeco for metrics (such as CPU/Memory/Disk) alerts, I'm using Prometheus (AlertManager). Therefore, I don't know `metrics_aggregation` works as expectedly... It is ElastAlert matter, not Praeco.

BTW, I fixed default ElastAlert config. Please update your config too.
https://github.com/daichi703n/praeco/commit/de736a9e887930e57afcc287ed4c1a64f421ad3d
If `buffer_time` is equal to or less than `run_every`, delayed log cannot be detected.

**Comment by daichi703n** [comment]
@suresh447 I have a request.
Are you using Kubernetes?
Would you please deploy my Praeco Helm Chart to your Kubernetes?
https://github.com/daichi703n/praeco-helm

I want to test and improve it, but I don't have real operational Kubernetes.

Please note that, the chart does not well tested, therefore, don't forget to backup rules (keep YAML plain text on outside of the pvc).

@johnsusek I'm planning to donate this Helm Chart to you as a Praeco Official in the future.

**Comment by suresh447** [comment]
@daichi703n Yes we are using kubernetes but i don't have permission to deploy anything in the cluster but let me try and let you know.

**Comment by daichi703n** [comment]
@suresh447 I see. Thanks. 
If you don't have any more question, please close this issue.

**Comment by suresh447** [comment]
Thanks for your support.
