### ISSUE TITLE
nginx:[emerg] host not found in upstream "api.github.com"

### ISSUE THREAD

**Issue by Akes712** [ServerCentral/praeco#188]
nginx:[emerg] host not found in upstream "api.github.com" in /etc/nginx/conf.d/default.conf. I'm trying to set up as docker. webapp is always exiting with code 1. The server is currently behind a proxy and require it to access it internet.

**Comment by daichi703n** [comment]
I reproduced your issue, and now checking how it resolve.
At a moment, you can run Praeco with comment out this section.
https://github.com/ServerCentral/praeco/blob/master/nginx_config/default.conf#L21-L24

**Comment by daichi703n** [comment]
Modifying `./nginx_config/default.conf` as below works for me.

```
  location /api-app/releases {
      proxy_cache github_api_cache;
      rewrite ^(.*)$ "://api.github.com/repos/ServerCentral/praeco/releases";
      rewrite ^(.*)$ "http$1" break;
      proxy_pass http://<PROXY_IP>:<PROXY_PORT>;
    #   proxy_pass https://api.github.com/repos/ServerCentral/praeco/releases;
  }
```

like this answer
https://serverfault.com/questions/583743/how-to-make-an-existing-caching-nginx-proxy-use-another-proxy-to-bypass-a-firewa

---

Also you can specify proxy_pass as `proxy_pass http://$HTTP_PROXY;` and specify env in `docker-compose.yml`.

```
  webapp:
    environment: 
      - "HTTP_PROXY=192.168.1.76:8080"
```

**Comment by Akes712** [comment]
Thank you this worked!
