### ISSUE TITLE
Tagging Dockerhub images

### ISSUE THREAD

**Issue by jfcantu** [ServerCentral/praeco#194]
Hi!

Is there a reason the Dockerhub images for Praeco and Elastalert aren't tagged? We like to pin our Dockerfiles and Nomad jobs to specific versions, but these images only have the "latest" tag.

(I can pin it to the digest, but tagging is a bit cleaner.)

**Comment by daichi703n** [comment]
Same issue? https://github.com/ServerCentral/praeco/issues/166#issuecomment-544550683

Future releases will be tagged.

**Comment by jfcantu** [comment]
Yes indeed - sorry, I didn't search the closed issues.
