### ISSUE TITLE
Errno 99 when testing rule with "Send real alerts"

### ISSUE THREAD

**Issue by scott-oit** [ServerCentral/praeco#196]
If I enable "Send real alerts", I get the following:

```
Test run error
ERROR:root:Error while running alert email: Error connecting to SMTP host: [Errno 99] Address not available
```

![image](https://user-images.githubusercontent.com/45404878/79280276-da266480-7e64-11ea-8203-3db10ffd4823.png)

If I save the rule, it seems to function just fine. I still get alerts like normal. I'm using basic SMTP, no auth, no special port. This is the only thing set in my base_rule.config. I've also tried the IP.

```
smtp_host: 'smtp.dns.name'
smtp_port: 25
```

I'm running it Praeco via Docker. Any ideas? Where can I look for logs? I'm hoping it's simple.

Thank you!

**Comment by daichi703n** [comment]
Hi, @scott-oit 
Original ElastAlert (base of `servercentral/elastalert`)(not Praeco) has some bugs. I faced this issue too and I fixed on my own.
For experimental use, I created fixed image `daichi703n/elastalert:0.2.1-dev`. If you can test, please replace your elastalert docker image on `docker-compose.yml`.

### Fixed issues
- Can't run test rule
- Enable/Disable does not work
- Keep remains deleted rule

I'm continuously testing for merging my fixes to original repo.

**Comment by scott-oit** [comment]
@daichi703n That is working! Thank you!

**Comment by daichi703n** [comment]
@scott-oit Great!
Could you please use `daichi703n/elastalert:0.2.1-dev2`?
I just merged fixing about **Alert log does not written**, by @jfcantu .

**Comment by scott-oit** [comment]
I tried it, but I get the following error when testing rules, now. I'm swapped back to ```daichi703n/elastalert:0.2.1-dev``` and the error goes away.

```Test run error
Error running your filter:
TypeError("search() got multiple values for argument 'body'",)
INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
```

![image](https://user-images.githubusercontent.com/45404878/79359430-74cf8380-7ef7-11ea-8af9-77f49cfe15fe.png)

**Comment by daichi703n** [comment]
@scott-oit Thanks. Hmm... I'll re-test. Please use `0.2.1-dev`.

**Comment by jfcantu** [comment]
It appears this is broken in ElastAlert itself.

In `elasticsearch-py` v7.5.0, they changed up the parameters to the `client.search()` function:

Old definition: `def search(self, index=None, body=None, params=None):`
New definition: `def search(self, body=None, index=None, doc_type=None, params=None):`.

ElastAlert doesn't pass `index` as a named parameter ([see here](https://github.com/Yelp/elastalert/blob/4ebdabfc4d7705520fb823607a481237f0663ff1/elastalert/test_rule.py#L86)) so the change to `elasticsearch-py` broke that functionality:

`res = es_client.search(index, size=1, body=query, ignore_unavailable=True)`

**Comment by nsano-rururu** [comment]
@daichi703n

I found that the problem that occurs in the @scott-oit environment can be solved by changing the source code of ElastAlert as follows.

**test_rules.py**

**Line86**

res = es_client.search(index, size=1, body=query, ignore_unavailable=True)
↓
res = es_client.search(index=index, size=1, body=query, ignore_unavailable=True)

**Line112**

res = es_client.count(index, doc_type=doc_type, body=count_query, ignore_unavailable=True)
↓
res = es_client.count(index=index, doc_type=doc_type, body=count_query, ignore_unavailable=True)

**Line 156**

res = es_client.search(index, size=args.max_query_size, body=query, ignore_unavailable=True)
↓
res = es_client.search(index=index, size=args.max_query_size, body=query, ignore_unavailable=True)

**Comment by nsano-rururu** [comment]
@daichi703n

|  elasticsearch-py   |  Test Run   |   Send real alerts  | 
| --- | --- | --- | 
|  7.0.0    |  〇    |  〇   | 
|  7.10.0    |  ✖    |  ✖   |
|  7.10.0    |  ✖    |  ✖   |
|  7.10.0    | 〇<br> (fix test_rules.py )    |  ✖   |
|  7.10.0    | 〇<br> (fix test_rules.py )    |  〇<br>([Fix initializing self.thread_data.alerts_sent for running elastalert-test-rule #2991](https://github.com/Yelp/elastalert/pull/2991))   |
