### ISSUE TITLE
Getting 403 Client Error

### ISSUE THREAD

**Issue by tbhaxor** [ServerCentral/praeco#202]
When i had added the correct slack webhook in `BaseRule.config`, I am getting `Error posting to slack: 403 Client Error: Forbidden for url: MY WEBHOOK URL`

**Comment by nsano-rururu** [comment]
@tbhaxor 

Does BaseRule.config look like this:

The part where "xxxxxx / xxxxxx / xxxxxx" differs depending on the target WEBHOOK

```
slack_webhook_url: 'https://hooks.slack.com/services/xxxxxx/xxxxxx/xxxxxx'
```

Slack Setting

Did you specify #Channel Name for Channel or username?
Did you specify a user name for Post as?

![2](https://user-images.githubusercontent.com/22293449/80306559-09db5200-87ff-11ea-8c97-c8649a197aa3.PNG)

In my environment, there are alerts.
![3](https://user-images.githubusercontent.com/22293449/80306691-c6cdae80-87ff-11ea-85e9-547c3efa12d6.PNG)

**Comment by tbhaxor** [comment]
The channel name is `#notifications` and webhook URL exists in my BaseRule.config. I can post on the slack with CURL

**Comment by nsano-rururu** [comment]
I set the webhook_url setting on the following screen, but how did you set it?

![1](https://user-images.githubusercontent.com/22293449/80613849-bbd18300-8a78-11ea-96ff-dd6ca71fff4f.PNG)
![2](https://user-images.githubusercontent.com/22293449/80613880-c25ffa80-8a78-11ea-8dde-2b61a1f79b91.PNG)
![3](https://user-images.githubusercontent.com/22293449/80613917-cab83580-8a78-11ea-84e2-e264641da3a2.PNG)
![3](https://user-images.githubusercontent.com/22293449/80613948-d3a90700-8a78-11ea-9206-ad866b39ae1a.PNG)
![4](https://user-images.githubusercontent.com/22293449/80613965-d73c8e00-8a78-11ea-9fa3-297b9e3f3940.PNG)
![5](https://user-images.githubusercontent.com/22293449/80613978-dad01500-8a78-11ea-8e73-ce91bdc5e80b.PNG)

**Comment by tbhaxor** [comment]
I used the same order of steps to set up slack with praeco. I reinstalled my setup to ensure any conflict or error, but unfortunately same 403 error

**Comment by nsano-rururu** [comment]
From the findings below, I don't know anything more than the incorrect Web hook URL in BaseRule.config. I'm sorry.

If you make a mistake in the channel name, 404

```
16:19:26.130Z ERROR elastalert-server:
    ProcessController:  /home/node/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'hooks.slack.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    ERROR:root:Error while running alert slack: Error posting to slack: 404 Client Error: Not Found for url: Correct web hook URL
```

If you make a mistake in the Web hook URL, 403

```
16:44:23.011Z ERROR elastalert-server:
    ProcessController:  /home/node/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:979: InsecureRequestWarning: Unverified HTTPS request is being made to host 'hooks.slack.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    ERROR:root:Error while running alert slack: Error posting to slack: 403 Client Error: Forbidden for url: Incorrect web hook URL
```

**Comment by tbhaxor** [comment]
AFAIK, 404 != 403 unless the developers havent done so.

no problem, i'll take care from here.
