### ISSUE TITLE
Timestamp format issue when @timestamp is not in standard format, in our case it is in unixms format.

### ISSUE THREAD

**Issue by Sujeet1604** [ServerCentral/praeco#46]
ProcessController:  WARNING:elasticsearch:GET http://elasticdevl.rxcorp.com:80/.monitoring-es*/_search?_source_include=%40timestamp%2C%2A&ignore_unavailable=true&scroll=30s&size=10000 [status:400 request:0.017s]
elastalert_1  |     ERROR:root:Error running query: RequestError(400, u'search_phase_execution_exception', u'No mapping found for [@timestamp] in order to sort on')

**Comment by johnsusek** [comment]
@Sujeet1604 This will be fixed in 0.2

**Comment by johnsusek** [comment]
fixed in https://github.com/ServerCentral/praeco/commit/60833e62f01f932afde63a16d2eb533d07e6eda5

**Comment by johnsusek** [comment]
@Sujeet1604 v0.2 is now out, instructions to update are at https://github.com/ServerCentral/praeco/blob/master/UPGRADING.md Give it a try and let me know how it works
