### ISSUE TITLE
Running on Win2012 R2

### ISSUE THREAD

**Issue by prakash1243** [ServerCentral/praeco#53]
Hi-
I would like to run this service on a Windows 2012 R2 server? How do I do that?
Please let me know the steps. Thanks !

**Comment by johnsusek** [comment]
Hi, there are Windows instructions on the [walkthrough article](https://medium.com/@john_8166/praeco-walkthrough-5aada7e078a9). 

Basically:
```
$Env:PRAECO_ELASTICSEARCH="1.2.3.4"
docker-compose.exe up
```

Make sure you install Docker for windows first
