### ISSUE TITLE
Authenticated SSL Connection

### ISSUE THREAD

**Issue by berniemoran** [ServerCentral/praeco#55]
With Elastalert server there are options to connect to Elasticsearch over SSL using credentials. Is it possible to configure Praeco in a similar way to be able to create the write back instance? Ref. https://github.com/ServerCentral/praeco/blob/master/config/api.config.json

**Comment by johnsusek** [comment]
You can change any elastalert server settings by editing this file:
https://github.com/ServerCentral/praeco/blob/master/config/elastalert.yaml

https://github.com/ServerCentral/praeco/blob/master/config/api.config.json is just configuration for the api, not elastalert itself. 

But if you are changing your writeback_index, make sure it matches in both files. The api needs to know the writeback_index to fetch the logs.

**Comment by berniemoran** [comment]
Will have to re-open this one. Everything works fine with the Elastalert Server connecting to an SSL Elasticsearch cluster using authentication and the praeco_elastalert_status index is successfully created.
But when entering the UI and attempting to create a new rule then http is used instead of https and the request fails.

05:50:22.407Z  INFO elastalert-server: ProcessController:  Creating index
05:50:27.063Z  INFO elastalert-server:
    ProcessController:  Elastic Version:6
    Mapping used for string:{'type': 'keyword'}
    New index praeco_elastalert_status created
    Done!

05:50:27.063Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
05:50:27.064Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
05:50:27.071Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 36)
05:50:27.074Z  INFO elastalert-server: Server:  Server listening on port 3030
05:50:27.079Z  INFO elastalert-server: Server:  Websocket listening on port 3333
05:50:27.080Z  INFO elastalert-server: Server:  Server started
Elasticsearch ERROR: 2018-12-16T05:53:39Z
  Error: Request error, retrying
  GET http://es-master:9200/_cat/indices?h=index => socket hang up
      at Log.error (/opt/elastalert-server/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/opt/elastalert-server/node_modules/elasticsearch/src/lib/transport.js:259:18)
      at HttpConnector.<anonymous> (/opt/elastalert-server/node_modules/elasticsearch/src/lib/connectors/http.js:163:7)
      at ClientRequest.wrapper (/opt/elastalert-server/node_modules/lodash/lodash.js:4949:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketOnEnd (_http_client.js:433:9)
      at Socket.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)

Elasticsearch WARNING: 2018-12-16T05:53:39Z
  Unable to revive connection: http://es-master:9200/

**Comment by johnsusek** [comment]
@berniemoran I just pushed a change, can you run these commands and try again:

- `docker pull servercentral/praeco && docker pull servercentral/elastalert`
- `docker-compose up --force-recreate --build && docker image prune -f`

**Comment by berniemoran** [comment]
I can confirm that this works and that the UI is now functional. 
Would it also be possible to have each request sent with the user credentials set in the Elastalert Server configuration es_username, es_password (https://github.com/ServerCentral/praeco/blob/58f21635d0f6d6b80f70095a3a070da6f84a4d8f/config/elastalert.yaml#L38)? Just that the requests are anonymous at this stage, which makes it difficult to set up back-end access roles.

**Comment by johnsusek** [comment]
@berniemoran Sure, I'm creating a new issue for that and closing this one
