### ISSUE TITLE
Add support for user credentials for api->es

### ISSUE THREAD

**Issue by johnsusek** [ServerCentral/praeco#66]
https://github.com/ServerCentral/praeco/issues/55#issuecomment-447678585

**Comment by emcnicholl** [comment]
Hi John, this would be very useful. Any idea when we might expect it? Thanks

**Comment by johnsusek** [comment]
@emcnicholl @DanMcKinney Just pushed out a new release with auth support. I don't have access to a cluster with auth enabled, so it is untested. Can you give it a try when you get a chance? Add options `es_username` and `es_password` to api.config.json. Let me know how it turns out. Thanks!

**Comment by berniemoran** [comment]
@johnsusek I have tested this release with a Searchguard auth enabled cluster and it works fine. All Praeco indexes are created and API calls are made with the configured username.

**Comment by emcnicholl** [comment]
@johnsusek also tested with Searchguard, working as expected, thanks!

**Comment by johnsusek** [comment]
Great, thanks!
