### ISSUE TITLE
Save button  always stay saving.

### ISSUE THREAD

**Issue by dmrSec** [ServerCentral/praeco#75]
Hi everybody

I configured now praeco and setup new alert, but after click on save button not works, the process keeps saving but not save.
in the container it does not record/save any error log, and any log or error is generated in GUI or containers logs.

But in test query, is possible show test button that query get results, but the save button always stay saving...
Bellow the prints.

![save-error](https://user-images.githubusercontent.com/46447107/50779406-5fe15a80-1287-11e9-8dc4-00b4ff22fd95.png)
![step-1](https://user-images.githubusercontent.com/46447107/50779407-5fe15a80-1287-11e9-84d7-181333188161.png)
![step-2](https://user-images.githubusercontent.com/46447107/50779408-5fe15a80-1287-11e9-8d2a-ba7156dc18ae.png)
![step-4](https://user-images.githubusercontent.com/46447107/50779409-5fe15a80-1287-11e9-8bba-e6c7b8c17429.png)

Using docker to connect in slaticsearch, elasticsearch without ssl and xpack module.
Some can help.

Thanks

**Comment by johnsusek** [comment]
I think you just need to set a threshold ("is above/below", or "is not empty") for your alert:

![50779407-5fe15a80-1287-11e9-84d7-181333188161](https://user-images.githubusercontent.com/611996/50782435-9a3dfe00-126d-11e9-8dbb-32e35233a15c.png)

**Comment by dmrSec** [comment]
Hi johsusek, 

Sorry, i had checked it, after take a screenshot.
I forget of update the screenshot.
Try using another browser, like firefox, not works
Try up the localhost the compose and set to my elasticsearch server, not works to.

**Comment by dmrSec** [comment]
[alert_saving.mp4.zip](https://github.com/ServerCentral/praeco/files/2734176/alert_saving.mp4.zip)

Hi, put a movie to show more details.

thanks

**Comment by 2arunpmohan** [comment]
The same issue for me also.
[Here ](https://drive.google.com/file/d/1yCTZm6NA0i0eX9ehRLwauy6NEeSw5Xqm/view?usp=sharing)is the error in browser console, that is occurring when pressing the "Save" button

**Comment by dmrSec** [comment]
Same issue too.

I forgot to look at the browser console errors.

**Comment by dmrSec** [comment]
Hi @2arunpmohan you got resolve this in your environment ?

**Comment by 2arunpmohan** [comment]
> Hi @2arunpmohan you got resolve this in your environment ?

Nope. No luck so far. How about you?

**Comment by dmrSec** [comment]
no way too.
Trying use elastalert only until resolve this.

**Comment by johnsusek** [comment]
I put out a hotfix for this, run these commands to update:

```
docker pull servercentral/praeco && docker pull servercentral/elastalert
docker-compose up --force-recreate --build && docker image prune -f
```

Please confirm fix so I can close issue.

@2arunpmohan thx for console error, it helped a lot

**Comment by dmrSec** [comment]
@johnsusek thanks champ.

give your paypal account to donate  a coffee =)

**Comment by johnsusek** [comment]
No need for donations, instead check out the sponsor https://www.servercentral.com/ if your company needs datacenter space or high availability hosting. Yes, we have experience hosting massive ES clusters :)
