### ISSUE TITLE
Not able to add whitelist conditions

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#76]
Iam using Praeco version  0.3.0 .
How can I create a whitelist rule using the UI?. 
I was able to create some successful frequency alerts (which is the default, rule I guess), but for whitelisting a set of values, how shall I proceed?. Do I need to add that manually in the rules file, but if that is so, it negates the use of the UI, right?. 
Can anyone comment on this?

**Comment by johnsusek** [comment]
select "WHEN field not in list" by clicking on the word "WHEN" and selecting from dropdown.
