### ISSUE TITLE
FEATURE: Praeco as kibana plugin

### ISSUE THREAD

**Issue by homa1978** [ServerCentral/praeco#78]
hi

it would be nice to have praeco as kibana plugin direct integrated in kibana in the left menu like the bitsensor implementation.

br 
Mario

**Comment by johnsusek** [comment]
Hi, thanks for suggesting this feature. It would indeed be handy to have praeco within kibana. Sadly, this would require massive changes in the core structure of the way the app works. Basically praeco was written with the assumption of being its own standalone thing, so putting it within kibana now is just prohibitively complex.
