### ISSUE TITLE
Not able to trigger events for a single occurrence

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#87]
Following is the screenshot of my rules and I want it to alert for a one or more occurrance. That is any count greater than or equal to 1. With the below config, I am not able to achieve the same.
![praeco_bug_02](https://user-images.githubusercontent.com/9315301/52033228-334cf580-254a-11e9-9f68-53bb6ab16b47.png)

I believe there is a way for doing exactly the same. But I am not able to find the same in Praeco.
 Can anyone please help on this?

**Comment by johnsusek** [comment]
Select "Is Not Empty" from the dropdown:

![screen shot 2019-01-31 at 8 05 32 am](https://user-images.githubusercontent.com/611996/52059267-03dcbf80-252f-11e9-8b76-740f2ee6e3ff.png)
