### ISSUE TITLE
Not able to alert against a numerical field

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#88]
I have a field named "numValue", which might range from -50 to +50. 
I tried to setup a rule such that, an alert will generate whenever the "numValue" is greater than 30. Is this possible in Praeco?

**Comment by johnsusek** [comment]
Yes, a filter like this should do what you want:

![screen shot 2019-02-13 at 8 33 35 am](https://user-images.githubusercontent.com/611996/52718891-1bbe3580-2f6a-11e9-994b-40ccf8bd414e.png)
