### ISSUE TITLE
groupOver field not being remembered

### ISSUE THREAD

**Issue by youlJunior** [ServerCentral/praeco#89]
Hello,

The "groupOver" field is retained in UI only for "frequency" or "flatline" rule types.
(see commit b62f5b8c3f7feae74a1b14f8ac5454adf09965ef)

But, as Yelp/elastlert documentation show, "query_key" can be used for other rule types (Metric aggregation by example : https://github.com/Yelp/elastalert/blob/master/docs/source/ruletypes.rst#metric-aggregation)

So when I make a group query on a metric aggregation rule, it is written in rule.yml file, but everytime I edit the rule in UI, I have to select group field again.

**Comment by youlJunior** [comment]
@johnsusek 
I removed the condition over rule type : 
`(this.type === 'frequency' || this.type === 'flatline')`
After rebuild, I can make group over a field for any type of rule.

**Comment by johnsusek** [comment]
@youlJunior Thanks, that helped. I've fixed this, will go out in next release.
