### ISSUE TITLE
Error while loading template with yml extension

### ISSUE THREAD

**Issue by youlJunior** [ServerCentral/praeco#90]
In the template bundled with elastalert-server, there is 2 with yml extension, while the others are with yaml extension.
-> spike_template.yml and threshold_template.yml

In the preaco GUI, those 2 templates are shown with .yml extension (while the others are shown without ext), and when Praeco try to get them vie API, it gets a 404 error.

Renaming the template from .yml to .yaml resolve the problem, but maybe it's in the ReactJS classes where there is a filter on .yaml ext.

**Comment by johnsusek** [comment]
These default templates are not meant to be used with praeco. I'll update our fork of elastalert-server to remove them. Tracked in #91
