### ISSUE TITLE
Filter error loading some templates

### ISSUE THREAD

**Issue by adrienyhuel** [ServerCentral/praeco#91]
When Praeco GUI try to read some bundled templates, there is an error.

Affected templates are : 
integration_started_template
no_data_template
spike_template
threshold_template

The error shown in GUI is : "TypeError: c.filter is undefined"

**Comment by youlJunior** [comment]
It seems that adding a first line on those templates, like this make them work : 
__praeco_query_builder: '{"query":{"logicalOperator":"all","children":[]}}'

It may be in Praeco Javascript, for those type of rules.

**Comment by johnsusek** [comment]
These default templates are not meant to be used with praeco. I'll update our fork of elastalert-server to remove them
