### ISSUE TITLE
What really happens when a rule is disabled?

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#94]
When we make a rule disabled in the Praeco, will it stop running the queries to Elasticsearch?
Or will it just stop alerting,but still queries Elasticsearch?

**Comment by johnsusek** [comment]
Disabling a rule is meant to stop alerting and stop querying (eventually).

Praeco simply sets is_enabled to false in the rule .yaml file. 

Elastalert notices this change and will stop querying for the next run of its rule. We have noticed that the alerts will not stop immediately, but will stop on their "next run". So if you have a rule checking, for example, "SPIKES 2X FOR THE LAST 10 MINUTES", then it may take up to 10 minutes to disable this rule. 

We have also noticed that restarting elastalert seems to disable the rule immediately. You can restart the elastalert within the docker image with this command in the praeco directory:
`docker-compose up --force-recreate --build`

Here is relevant source code from elastalert project: https://github.com/Yelp/elastalert/pull/1428
