### ISSUE TITLE
Is Praeco YAML same as Elastalert YMLs?

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#97]
I want to port my Praeco rules to Elastalert rules. But I see the YAML for Praeco differring from that of Elastalert format. 
My questions are 
1. can I use Praeco rule YAMLs to convert to Elastalert rules?
2. or if straight away, not possible what is the way to convert Praeco rules to Elastalert rules?.

Can someone help me on this?

**Comment by johnsusek** [comment]
Praeco rules are compatible with elastalert. Just drop the praeco-created rules into another elastalert instance and you should be g2g.
