### ISSUE TITLE
How to make Praeco query only relevant indices?

### ISSUE THREAD

**Issue by 2arunpmohan** [ServerCentral/praeco#98]
I have to check for daily alerts. My index pattern is test-index-YYYY-MM-DD. But inorder to avoid, frequent updating of rules, I have added the index pattern as "test-index-*". 
But over time, this pattern leads to querying more indices, that is for searching for a single day, this pattern leads to searching for a lot of irrelevant queries.  
I have found an option like (marked in red box) in the below screenshot, but how can I make it working?
![index_pattern](https://user-images.githubusercontent.com/9315301/52903141-9a9fc080-323f-11e9-92ad-84680fa15f6e.png)

**Comment by johnsusek** [comment]
you should make your index name this:
`winlogbeat-6.4.0-%Y.%m.d`

%Y, %m and %d will be replaced by today's year, month and day.

**Comment by 2arunpmohan** [comment]
@johnsusek 
Yes, it should ideally work.
But, this is what I am getting.
![praeco_bug_follow_up](https://user-images.githubusercontent.com/9315301/52936721-0b032a80-3383-11e9-92c0-baa0889bc3bb.PNG)

As you can see, this is not picking up the data. 
I have enabled the use_strftime_index to true in the config folder too.

**Comment by shailendher** [comment]
I have the same issue as well.
From the console, it looks like the placeholders are not being replaced in [ESChart.vue](https://github.com/ServerCentral/praeco/blob/master/src/components/ESChart.vue#L601)
Perhaps the index variable should have been formatted with [formatIndex](https://github.com/ServerCentral/praeco/blob/master/src/lib/elasticSearchMetadata.js#L1) everywhere?

![image](https://user-images.githubusercontent.com/142674/53237629-73aa1a00-3697-11e9-8594-1d9dd1e21005.png)

**Comment by johnsusek** [comment]
Hey all - this is fixed now in v0.3.3. Thanks for the reports!
